### ISSUE TITLE
Drush not installed when running blt deploy

### ISSUE THREAD

**Issue by bobbygryzynger** [acquia/blt#1528]
My system information:
* Operating system type: macOS
* Operating system version: 10.12.5
* BLT version: 8.7.3

Output of `blt doctor`:
```
blt > doctor:
Changed current directory to /home/vagrant/.composer
+----------------------+----------------------------------------------------------------------------------+
| Property             | Value                                                                            |
+----------------------+----------------------------------------------------------------------------------+
| %paths               |                                                                                  |
|  - %root             | /var/www/<site>/docroot                                                         |
|  - %site             | sites/default                                                                    |
|  - %modules          | modules                                                                          |
|  - %themes           | themes                                                                           |
|  - %config-sync      | /var/www/<site>/config/default                                                  |
|  - %files            | sites/default/files                                                              |
|  - %private          | /var/www/<site>/files-private                                                   |
|  - %temp             | /tmp                                                                             |
| admin-theme          | seven                                                                            |
| blt-version          | 8.7.3                                                                            |
| bootstrap            | Successful                                                                       |
| config-sync          | /var/www/<site>/config/default                                                  |
| db-driver            | mysql                                                                            |
| db-hostname          | localhost                                                                        |
| db-name              | <site>_default                                                                  |
| db-password          | admin                                                                            |
| db-port              | 3306                                                                             |
| db-status            | Connected                                                                        |
| db-username          | admin                                                                            |
| drupal-settings-file | sites/default/settings.php                                                       |
| drupal-version       | 8.2.8                                                                            |
| drush-alias-files    | /var/www/<site>/docroot/../drush/site-aliases/aliases.drushrc.php               |
|                      | /var/www/<site>/docroot/../drush/site-aliases/example.acsf.aliases.drushrc.php  |
|                      | /var/www/<site>/docroot/../drush/site-aliases/example.local.aliases.drushrc.php |
| drush-conf           | /var/www/<site>/drush/drushrc.php                                               |
| drush-script         | /var/www/<site>/vendor/drush/drush/drush.php                                    |
| drush-temp           | /tmp                                                                             |
| drush-version        | 8.1.10                                                                           |
| files                | sites/default/files                                                              |
| install-profile      | standard                                                                         |
| local-settings       | /var/www/<site>/docroot/sites/default/settings/local.settings.php               |
| modules              | modules                                                                          |
| php-bin              | /usr/bin/php                                                                     |
| php-conf             | /etc/php/5.6/cli/php.ini                                                         |
| php-os               | Linux                                                                            |
| private              | /var/www/<site>/files-private                                                   |
| root                 | /var/www/<site>/docroot                                                         |
| site                 | sites/default                                                                    |
| temp                 | /tmp                                                                             |
| theme                | meyers                                                                           |
| themes               | themes                                                                           |
| uri                  | default                                                                          |
| user                 |                                                                                  |
+----------------------+----------------------------------------------------------------------------------+
+--------------------------+----------------------------------------------------------------------------------+
| Check                    | Outcome                                                                          |
+--------------------------+----------------------------------------------------------------------------------+
| checkDocrootExists       | Found docroot.                                                                   |
| checkCoreExists          | Drupal core exists                                                               |
| checkSettingsFile        | BLT settings are included in settings file.                                      |
| checkLocalSettingsFile   | Found your local settings file.                                                  |
| checkLocalDrushFile      | Local drushrc file does not exist.                                               |
|                          | Create /var/www/<site>/docroot/sites/default/local.drushrc.php.                 |
|                          | Run `blt setup:drush:settings` to generate it automatically, or run `blt setup`  |
|                          | to run the entire setup process.                                                 |
| checkFileSystem:%files   | Public files directory is writable.                                              |
| checkFileSystem:%private | Private files directory is writable.                                             |
| checkFileSystem:%temp    | Temporary files directory is writable.                                           |
| checkDbConnection        | Connected to database.                                                           |
| checkDrupalBootstrapped  | Bootstrapped Drupal via drush.                                                   |
| checkDrupalInstalled     | Drupal is installed.                                                             |
| checkCaching:page        | Drupal cache is disabled.                                                        |
| checkCaching:css         | CSS preprocessing is disabled.                                                   |
| checkCaching:js          | JS preprocessing is disabled.                                                    |
| checkNvmExists           | NVM does not exist.                                                              |
|                          |                                                                                  |
|                          | It is recommended that you use NVM to manage multiple versions of NodeJS on one  |
|                          | machine.                                                                         |
|                          | Instructions for installing NVM can be found at:                                 |
|                          |   https://github.com/creationix/nvm#installation                                 |
| checkComposer:require    | acquia/blt is in composer.json's require object.                                 |
| checkComposer:plugins    | hirak/prestissimo plugin for composer is installed.                              |
| checkBehat:exists        | Behat local settings file exists.                                                |
| checkBehat:uri           | base_url in tests/behat/local.yml does not match the site URI.                   |
|                          |   Behat base_url is set to "http://<site>.local".                               |
|                          |   Drush site URI is set to default.                                              |
| checkProjectYml:keys     | project.yml has no deprecated keys.                                              |
| checkAcsfConfig          | BLT settings are included in your pre-settings-php include.                      |
| checkSimpleSamlPhp       | /var/www/<site>/docroot/../vendor/simplesamlphp/simplesamlphp/metadata/saml20-i |
|                          | dp-remote.php is missing. Run `blt simplesamlphp:build:config`.                  |
| checkPhpDateTimezone     | PHP setting for date.timezone is correctly set                                   |
+--------------------------+----------------------------------------------------------------------------------+

```

When I run this command:
```
blt deploy:build
```

No `deploy/vendor/drush` is installed. If I delete my root `vendor` directory and run `composer install` `drush` is installed as expected. Within both my root and `deploy` `composer.lock` files I have the following `drush` entry:
```json
{
            "name": "drush/drush",
            "version": "8.1.10",
            "source": {
                "type": "git",
                "url": "https://github.com/drush-ops/drush.git",
                "reference": "2192496b80aa9cdb0581a2d308623f950f747e94"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/drush-ops/drush/zipball/2192496b80aa9cdb0581a2d308623f950f747e94",
                "reference": "2192496b80aa9cdb0581a2d308623f950f747e94",
                "shasum": ""
            },
            "require": {
                "consolidation/annotated-command": "~2",
                "consolidation/output-formatters": "~3",
                "pear/console_table": "~1.3.0",
                "php": ">=5.4.5",
                "phpdocumentor/reflection-docblock": "^2.0",
                "psr/log": "~1.0",
                "psy/psysh": "~0.6",
                "symfony/console": "~2.7",
                "symfony/event-dispatcher": "~2.7",
                "symfony/finder": "~2.7",
                "symfony/var-dumper": "~2.7",
                "symfony/yaml": "~2.3",
                "webmozart/path-util": "~2"
            },
            "require-dev": {
                "phpunit/phpunit": "4.*",
                "symfony/process": "2.7.*"
            },
            "suggest": {
                "drush/config-extra": "Provides configuration workflow commands, such as config-merge.",
                "ext-pcntl": "*"
            },
            "bin": [
                "drush",
                "drush.launcher",
                "drush.php",
                "drush.complete.sh"
            ],
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "8.0.x-dev"
                }
            },
            "autoload": {
                "psr-0": {
                    "Drush": "lib/",
                    "Consolidation": "lib/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "GPL-2.0+"
            ],
            "authors": [
                {
                    "name": "Moshe Weitzman",
                    "email": "weitzman@tejasa.com"
                },
                {
                    "name": "Owen Barton",
                    "email": "drupal@owenbarton.com"
                },
                {
                    "name": "Mark Sonnabaum",
                    "email": "marksonnabaum@gmail.com"
                },
                {
                    "name": "Antoine Beaupré",
                    "email": "anarcat@koumbit.org"
                },
                {
                    "name": "Greg Anderson",
                    "email": "greg.1.anderson@greenknowe.org"
                },
                {
                    "name": "Jonathan Araña Cruz",
                    "email": "jonhattan@faita.net"
                },
                {
                    "name": "Jonathan Hedstrom",
                    "email": "jhedstrom@gmail.com"
                },
                {
                    "name": "Christopher Gervais",
                    "email": "chris@ergonlogic.com"
                },
                {
                    "name": "Dave Reid",
                    "email": "dave@davereid.net"
                },
                {
                    "name": "Damian Lee",
                    "email": "damiankloip@googlemail.com"
                }
            ],
            "description": "Drush is a command line shell and scripting interface for Drupal, a veritable Swiss Army knife designed to make life easier for those of us who spend some of our working hours hacking away at the command prompt.",
            "homepage": "http://www.drush.org",
            "time": "2017-02-23T20:46:12+00:00"
        }
```

It's unclear to me what about running `blt deploy:build` would prevent the package from being installed in `deploy/vendor` as expected. If I cd into `deploy` and run `composer install`, the package is installed.

For sanity's sake I also ran `composer self-update` but the behavior I'm seeing did not change.

After running `blt deploy:build`, `deploy/vendor/` looks like this: 
<img width="265" alt="screen shot 2017-05-19 at 3 24 03 pm" src="https://cloud.githubusercontent.com/assets/6345927/26263548/4489f7d6-3ca7-11e7-83a8-30b7a8da3e52.png">

**Comment by bobbygryzynger** [comment]
I also want to add here that I ran into #1510 while attempting to update to `8.7.3` so I can't be certain that all necessary updates were performed.

**Comment by grasmash** [comment]
This has been resolved by the PR for #1510.

**Comment by bobbygryzynger** [comment]
@grasmash I'm still seeing this issue after upgrading to `8.7.3` using the patch from #1510.
