### ISSUE TITLE
Git commit messages are not being validated.

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#840]
My system information:
* Operating system type: macOS
* Operating system version: 10.12.2
* BLT version: 8.6.4

When I run this command:
```
git commit -m "Test."
```

I get the following output:
```
Sniffing staged files via PHP Code Sniffer...
Linting custom twig files...
Validating composer.json...
Ok!
PHP Warning:  Invalid argument supplied for foreach() in /Users/jeff.geerling/Sites/acquia/projectname/vendor/drupal/console/src/Utils/RequirementChecker.php on line 71
[feature-branch d6a2246] Test.
 1 file changed, 1 insertion(+)
```

And I expected this to happen:

- The commit message should be rejected because it doesn't have "PROJECT-[issue]: Commit string here."

I ran `blt setup:git-hooks` just before to verify the git hooks were installed correctly... so I'm not sure why the git commit message isn't being validated.

**Comment by geerlingguy** [comment]
Possibly related? https://github.com/hechoendrupal/DrupalConsole/issues/2905

There is that warning in the `console` namespace.

**Comment by grasmash** [comment]
Yes, this is due to a console bug that has been fixed. But we are blocked on updating console due to hechoendrupal/DrupalConsole#2905.

**Comment by grasmash** [comment]
Workaround added to 8.x: https://github.com/acquia/blt/pull/834

**Comment by geerlingguy** [comment]
Following the instructions here (https://github.com/hechoendrupal/DrupalConsole/issues/2561#issuecomment-249088018) allowed me to commit without the PHP warning... but the validation is still not being run.

**Comment by geerlingguy** [comment]
Also confirmed the project prefix was detected via `./vendor/bin/drupal yaml:get:value blt/project.yml project.prefix`, and that the commit hooks are both in the right folder...

**Comment by geerlingguy** [comment]
I think I found the main issue—the `PREFIX` used in the commit-msg git hook is incorrect because of a timezone issue with Drupal Console.

See:

```
 15:41:01 ~/Sites/acquia/projectname $ PREFIX=$(./vendor/bin/drupal yaml:get:value ./blt/project.yml project.prefix)
 15:41:14 ~/Sites/acquia/projectname $ echo $PREFIX
PROJECTNAME // check The configuration "date.timezone" was missing and overwritten with "America/Tijuana".
```

There's some extra text in there (not sure what the `// check` is for, but the other thing looks like a PHP warning?).

**Comment by geerlingguy** [comment]
So... I set the timezone in PHP (configured it for my timezone in `/usr/local/etc/php/7.0/php.ini` (use `php -i | grep php.ini` to find where your CLI is picking up config)), and that warning went away.

But now Drupal Console is still printing out some extra stuff:

```
 15:44:17 ~/Sites/acquia/projectname $ ./vendor/bin/drupal yaml:get:value ./blt/project.yml project.prefix
PROJECTNAME
 // settings:set

                                                                                                                        
 [OK] Setting "checked" was set to "true"                                                                               
                                                                                                                        

```

**Comment by geerlingguy** [comment]
Nevermind... after running the command _again_, that message is going away. Ugh.

So to fix, it looks like you have to do the following:

  1. Run `./vendor/bin/drupal init` (see https://github.com/acquia/blt/pull/834)
  2. Follow these instructions to get Drupal Console's PHP detection working: https://github.com/hechoendrupal/DrupalConsole/issues/2561#issuecomment-249088018
  3. Set a `date.timezone` value in your system's CLI PHP configuration (use `php -i | grep php.ini` to find which `.ini` to edit).

**Comment by geerlingguy** [comment]
Yes! Works now:

```
$ git commit -m "Test."
Sniffing staged files via PHP Code Sniffer...
Linting custom twig files...
Validating composer.json...
Ok!
Invalid commit message. Commit messages must:
* Contain the project prefix followed by a hyphen
* Contain a ticket number followed by a colon and a space
* Be at least 15 characters long and end with a period.
Valid example: PROJECTNAME-135: Added the new picture field to the article feature.
```

**Comment by geerlingguy** [comment]
It works, but this is a heck of a lot of extra configuration to get commit message validation going :/

**Comment by grasmash** [comment]
A few todos from this:

- [ ] Add a check to `blt doctor` that verifies date.timezone is set.
- [ ] Improve the [commit-msg script](https://github.com/acquia/blt/blob/8.x/scripts/git-hooks/commit-msg#L8) so that it fails when $PREFIX is not set correctly.
